version: '3.8'

services:
  backend-service:
    build:
      context: /src/
      dockerfile: backend.dockerfile
      args:
        - REACT_APP_BACKEND_URL=http://localhost:8080
    image: radeczu/backend:3.5
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - REQUEST_ORIGIN=http://localhost:8082
      - REDIS_HOST=redis
      - POSTGRES_HOST=database
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - app-network

  frontend-service:
    build:
      context: /src/
      dockerfile: frontend.dockerfile
      args:
        - REACT_APP_BACKEND_URL=http://localhost:8080
    image: radeczu/frontend:3.5
    ports:
      - "5000:5000"
    depends_on:
      - backend-service
    networks:
      - app-network

networks:
  app-network:
    driver: bridge